### ISSUE TITLE
Website is down? 

### ISSUE THREAD

**Issue by barkanido** [rust-community/resources#22]
https://rust-community.github.io/resources

**Comment by JohnTitor** [comment]
Looks like `community.rs` is now unregistered, cc @skade do you know something?

**Comment by JoelMon** [comment]
Instead of pointing https://rust-community.github.io/resources to community.rs can we default back to git pages and display the repository in HTML?

**Comment by JohnTitor** [comment]
We've removed CNAME and the gh-pages links should work now (note that some other pages need to rebuild). It may take some time to refresh cache. Thanks for reporting!
